laravel/app/Http/routes.php
<?php

use App\Helpers\Tools;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\URL;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('a-abint', 'AAbintController@index')->name('a-abint');
    Route::get('associados', 'AssociadosController@index')->name('associados');

    Route::get('naotecidos/{submenu}', 'NaoTecidosController@index')->name('naotecidos.index');
    Route::get('naotecidos/list/{submenu}', 'NaoTecidosController@getDados')->name('naotecidos.getDados');
    Route::get('naotecidos/aplicacoes-a-z/{letra}', 'NaoTecidosController@getAplicacaoLetra')->name('naotecidos.getAplicacaoLetra');

    Route::get('texteis-tecnicos/{submenu}', 'TexteisTecnicosController@index')->name('texteis-tecnicos.index');
    Route::get('texteis-tecnicos/list/{submenu}', 'TexteisTecnicosController@getDadosTexteis')->name('texteis-tecnicos.getDadosTexteis');

    Route::get('informacao/{submenu}', 'InformacaoController@index')->name('informacao.index');
    Route::get('informacao/list/{submenu}', 'InformacaoController@getDadosInformacao')->name('informacao.getDadosInformacao');
    Route::get('informacao/publicacoes/download/{slug}', 'InformacaoController@downloadPublicacao')->name('publicacoes.download');
    Route::get('informacao/normas-e-ensaios/download/{slug}', 'InformacaoController@downloadNormaEnsaio')->name('normas-e-ensaios.download');
    Route::get('informacao/imprensa/{novidade}', 'InformacaoController@showNovidade')->name('novidades.show');
    Route::get('informacao/imprensa/download/{novidade}', 'InformacaoController@downloadNovidade')->name('novidades.download');
    Route::get('informacao/outros/{outro}', 'InformacaoController@showOutro')->name('outros.show');
    Route::get('informacao/outros/download/{outro}', 'InformacaoController@downloadOutro')->name('outros.download');

    Route::get('associe-se', 'AssocieSeController@index')->name('associe-se');
    Route::post('associe-se', 'AssocieSeController@post')->name('associe-se.post');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::post('busca', 'BuscaController@post')->name('busca.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Idiomas
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if (in_array($idioma, ['pt'])) {
            Session::put('locale', $idioma);
        }
        if (URL::previous() == route('busca.post')) {
            return redirect()->route('home');
        } else {
            return redirect()->back();
        }
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        Route::resource('banners', 'BannersController');
        Route::resource('objetivos', 'ObjetivosController');
        Route::resource('destaques', 'DestaquesController');
        Route::resource('institucional', 'InstitucionalController', ['only' => ['index', 'update']]);
        Route::resource('diretoria', 'DiretoriaController');
        Route::resource('associados', 'AssociadosController');
        Route::resource('comites', 'ComitesController', ['except' => 'show']);
        Route::resource('comites.associados', 'ComitesAssociadosController', ['only' => ['index', 'create', 'store', 'destroy']]);
        Route::group([
            'prefix'     => 'naotecidos',
            'namespace'  => 'NaoTecidos',
        ], function () {
            Route::resource('o-que-sao', 'NaoTecidosDefinicaoController', ['only' => ['index', 'update']]);
            Route::resource('historia', 'NaoTecidosHistoriaController', ['only' => ['index', 'update']]);
            Route::resource('materias-primas', 'NaoTecidosMatPrimasController', ['only' => ['index', 'update']]);
            Route::resource('como-sao-fabricados', 'NaoTecidosFabricacaoController', ['only' => ['index', 'update']]);
            Route::resource('transf-acabamento-conversao', 'NaoTecidosTransformacaoController', ['only' => ['index', 'update']]);
            Route::resource('classificacao', 'NaoTecidosClassificacaoController', ['only' => ['index', 'update']]);
            Route::resource('identificacao', 'NaoTecidosIdentificacaoController', ['only' => ['index', 'update']]);
            Route::resource('algumas-aplicacoes', 'NaoTecidosAlgumasAplicacoesController');
            Route::resource('aplicacoes-a-z', 'NaoTecidosAplicacoesController');
        });
        Route::group([
            'prefix'     => 'texteis-tecnicos',
            'namespace'  => 'TexteisTecnicos',
        ], function () {
            Route::resource('o-que-sao', 'TexteisTecDefinicaoController', ['only' => ['index', 'update']]);
            Route::resource('materias-primas', 'TexteisTecMatPrimasController', ['only' => ['index', 'update']]);
            Route::resource('como-sao-fabricados', 'TexteisTecFabricacaoController', ['only' => ['index', 'update']]);
            Route::resource('processos-transf-acabamento', 'TexteisTecProcessosController', ['only' => ['index', 'update']]);
            Route::resource('classificacao', 'TexteisTecClassificacaoController', ['only' => ['index', 'update']]);
            Route::resource('desempenho', 'TexteisTecDesempenhoController', ['only' => ['index', 'update']]);
            Route::resource('identificacao', 'TexteisTecIdentificacaoController', ['only' => ['index', 'update']]);
            Route::resource('aplicacoes', 'TexteisTecAplicacoesController', ['only' => ['index', 'update']]);
        });
        Route::group([
            'prefix'     => 'informacao',
            'namespace'  => 'Informacao',
        ], function () {
            Route::resource('publicacoes', 'PublicacoesController');
            Route::resource('cursos-e-eventos', 'EventosController');
            Route::resource('normas-e-ensaios', 'NormasEnsaiosController');
            Route::resource('novidades', 'NovidadesController'); // IMPRENSA
            Route::resource('outros', 'OutrosController');
        });
        Route::resource('associe-se', 'AssocieSeController', ['only' => ['index', 'update']]);
        Route::get('associe-se/contatos/{associe}/toggle', ['as' => 'painel.associe-se.contatos.toggle', 'uses' => 'ContatosAssocieSeController@toggle']);
        Route::resource('associe-se/contatos', 'ContatosAssocieSeController');
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');

        // Limpar caches
        Route::get('clear-cache', function () {
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('config:cache');

            return 'DONE';
        });
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Http/Controllers/InformacaoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Evento;
use App\Models\NormaEnsaio;
use App\Models\Novidade;
use App\Models\Outro;
use App\Models\Publicacao;
use Illuminate\Support\Facades\Lang;

class InformacaoController extends Controller
{
    public function index($submenu)
    {
        $publicacoes = null;
        $cursosEventos = null;
        $normasEnsaios = null;
        $novidades = null; // IMPRENSA
        $outros = null;

        setlocale(LC_TIME, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
        date_default_timezone_set('America/Sao_Paulo');

        // $relatorios = Relatorio::where('tipo', 'adição')->where('created_at', 'LIKE', "%$dia1%")->get();

        // $data = Novidade::where('data', '2022-02-01')->get();

        // $novidades2 = Novidade::ordenados()->get();

        // $datanow = strftime('%d %B %Y', strtotime($novidades2[2]->data));

        // dd($datanow);

        switch ($submenu) {
            case "publicacoes":
                $titulo = Lang::get('frontend.informacao.publicacoes');
                $publicacoes = Publicacao::ordenados()->get();
                break;
            case "cursos-e-eventos":
                $titulo = Lang::get('frontend.informacao.cursos-e-eventos');
                $cursosEventos = Evento::ordenados()->get();
                break;
            case "normas-e-ensaios":
                $titulo = Lang::get('frontend.informacao.normas-e-ensaios');
                $normasEnsaios = NormaEnsaio::ordenados()->get();
                break;
            case "imprensa":
                $titulo = Lang::get('frontend.informacao.imprensa');
                $novidades = Novidade::ordenados()->get();
                break;
            case "outros":
                $titulo = Lang::get('frontend.informacao.outros');
                $outros = Outro::ordenados()->get();
                break;
        }

        return view('frontend.informacao', compact('titulo', 'publicacoes', 'cursosEventos', 'normasEnsaios', 'novidades', 'outros'));
    }

    public function getDadosInformacao($submenu)
    {
        switch ($submenu) {
            case "publicacoes":
                $titulo = Lang::get('frontend.informacao.publicacoes');
                $resultado = Publicacao::ordenados()->get();
                break;
            case "cursos-e-eventos":
                $titulo = Lang::get('frontend.informacao.cursos-e-eventos');
                $resultado = Evento::ordenados()->get();
                break;
            case "normas-e-ensaios":
                $titulo = Lang::get('frontend.informacao.normas-e-ensaios');
                $resultado = NormaEnsaio::ordenados()->get();
                break;
            case "imprensa":
                $titulo = Lang::get('frontend.informacao.imprensa');
                $resultado = Novidade::ordenados()->get();
                break;
            case "outros":
                $titulo = Lang::get('frontend.informacao.outros');
                $resultado = Outro::ordenados()->get();
                break;
        }

        return response()->json(['submenu' => $submenu, 'resultado' => $resultado, 'titulo' => $titulo]);
    }

    public function showNovidade($novidade_slug)
    {
        $novidade = Novidade::where('slug', $novidade_slug)->first();

        return view('frontend.novidades-show', compact('novidade'));
    }

    public function showOutro($outro_slug)
    {
        $outro = Outro::where('slug', $outro_slug)->first();

        return view('frontend.outros-show', compact('outro'));
    }

    public function downloadPublicacao($slug)
    {
        $arquivo = Publicacao::where('slug', $slug)->select('arquivo')->first();

        $arquivoPath = public_path() . "/assets/pdf/" . $arquivo->arquivo;

        return response()->file($arquivoPath);
    }

    public function downloadNormaEnsaio($slug)
    {
        $arquivo = NormaEnsaio::where('slug', $slug)->select('arquivo')->first();

        $arquivoPath = public_path() . "/assets/pdf/" . $arquivo->arquivo;

        return response()->file($arquivoPath);
    }

    public function downloadNovidade($slug)
    {
        $arquivo = Novidade::where('slug', $slug)->select('arquivo')->first();

        $arquivoPath = public_path() . "/assets/pdf/" . $arquivo->arquivo;

        return response()->file($arquivoPath);
    }

    public function downloadOutro($slug)
    {
        $arquivo = Outro::where('slug', $slug)->select('arquivo')->first();

        $arquivoPath = public_path() . "/assets/pdf/" . $arquivo->arquivo;

        return response()->file($arquivoPath);
    }
}

laravel/app/Http/Controllers/Painel/Informacao/EventosController.php
<?php

namespace App\Http\Controllers\Painel\Informacao;

use App\Http\Controllers\Controller;
use App\Http\Requests\EventosRequest;
use App\Models\Configuracoes;
use App\Models\Evento;

class EventosController extends Controller
{
    public function index()
    {
        $registros = Evento::ordenados()->get();

        return view('painel.informacao.cursos-e-eventos.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.informacao.cursos-e-eventos.create');
    }

    public function store(EventosRequest $request)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Evento::upload_imagem();

            Evento::create($input);

            return redirect()->route('painel.informacao.cursos-e-eventos.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit($registro_id)
    {
        $registro = Evento::where('id', $registro_id)->first();

        return view('painel.informacao.cursos-e-eventos.edit', compact('registro'));
    }

    public function update(EventosRequest $request, $registro_id)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Evento::upload_imagem();

            $registro = Evento::where('id', $registro_id)->first();

            $registro->update($input);

            return redirect()->route('painel.informacao.cursos-e-eventos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy($registro_id)
    {
        try {
            $registro = Evento::where('id', $registro_id)->first();
            $registro->delete();

            return redirect()->route('painel.informacao.cursos-e-eventos.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/informacao/novidades/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>INFORMAÇÃO - Novidades/Imprensa /</small> Adicionar Novidade</h2>
    </legend>

    {!! Form::open(['route' => 'painel.informacao.novidades.store', 'files' => true]) !!}

        @include('painel.informacao.novidades.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/informacao/novidades/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>INFORMAÇÃO - Novidades/Imprensa /</small> Editar Novidade</h2>
    </legend>

    {!! Form::model($novidade, [
        'route'  => ['painel.informacao.novidades.update', $novidade->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.informacao.novidades.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/informacao/novidades/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('data', 'Data') !!}
    {!! Form::date('data', null, ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem', 'Imagem') !!}
    @if($submitText == 'Alterar')
    <img src="{{ url('assets/img/novidades/'.$novidade->imagem) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
    @endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('titulo_en', 'Título (INGLÊS)') !!}
    {!! Form::text('titulo_en', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('texto', 'Texto') !!}
    {!! Form::textarea('texto', null, ['class' => 'form-control ckeditor', 'data-editor' => 'textImage']) !!}
</div>

<div class="form-group">
    {!! Form::label('texto_en', 'Texto (INGLÊS)') !!}
    {!! Form::textarea('texto_en', null, ['class' => 'form-control ckeditor', 'data-editor' => 'textImage']) !!}
</div>

<div class="well form-group">
    {!! Form::label('arquivo', 'Arquivo') !!}
    @if($submitText == 'Alterar')
    @if($novidade->arquivo)
    <a href="{{ route('novidades.download', $novidade->slug) }}" target="_blank" style="display:block; margin-bottom: 10px; max-width: 100%;">{{ $novidade->titulo_arquivo }}</a>
    @endif
    @endif
    {!! Form::file('arquivo', ['class' => 'form-control']) !!}
</div>

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            {!! Form::label('titulo_arquivo', 'Título do arquivo') !!}
            {!! Form::text('titulo_arquivo', null, ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {!! Form::label('titulo_arquivo_en', 'Título do arquivo (INGLÊS)') !!}
            {!! Form::text('titulo_arquivo_en', null, ['class' => 'form-control']) !!}
        </div>
    </div>
</div>

<hr>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.informacao.novidades.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/informacao/novidades/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>
        INFORMAÇÃO - Novidades/Imprensa
        <a href="{{ route('painel.informacao.novidades.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Novidade</a>
    </h2>
</legend>


@if(!count($novidades))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else
<table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="novidades">
    <thead>
        <tr>
            <th>Ordenar</th>
            <th>Data</th>
            <th>Imagem</th>
            <th>Título</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($novidades as $novidade)
        <tr class="tr-row" id="{{ $novidade->id }}">
            <td>
                <a href="#" class="btn btn-info btn-sm btn-move">
                    <span class="glyphicon glyphicon-move"></span>
                </a>
            </td>
            <td>{{ strftime("%d/%m/%Y", strtotime($novidade->data)) }}</td>
            <td><img src="{{ asset('assets/img/novidades/home/'.$novidade->imagem) }}" style="width: 100%; max-width:100px;" alt=""></td>
            <td>{{ $novidade->titulo }}</td>
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.informacao.novidades.destroy', $novidade->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.informacao.novidades.edit', $novidade->id ) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@endsection