laravel/app/Http/routes.php
<?php

use App\Helpers\Tools;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\URL;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('a-abint', 'AAbintController@index')->name('a-abint');
    Route::get('associados', 'AssociadosController@index')->name('associados');

    Route::get('naotecidos/{submenu}', 'NaoTecidosController@index')->name('naotecidos.index');
    Route::get('naotecidos/list/{submenu}', 'NaoTecidosController@getDados')->name('naotecidos.getDados');
    Route::get('naotecidos/aplicacoes-a-z/{letra}', 'NaoTecidosController@getAplicacaoLetra')->name('naotecidos.getAplicacaoLetra');

    Route::get('texteis-tecnicos/{submenu}', 'TexteisTecnicosController@index')->name('texteis-tecnicos.index');
    Route::get('texteis-tecnicos/list/{submenu}', 'TexteisTecnicosController@getDadosTexteis')->name('texteis-tecnicos.getDadosTexteis');

    Route::get('informacao/{submenu}', 'InformacaoController@index')->name('informacao.index');
    Route::get('informacao/list/{submenu}', 'InformacaoController@getDadosInformacao')->name('informacao.getDadosInformacao');
    Route::get('informacao/publicacoes/download/{slug}', 'InformacaoController@downloadPublicacao')->name('publicacoes.download');
    Route::get('informacao/normas-e-ensaios/download/{slug}', 'InformacaoController@downloadNormaEnsaio')->name('normas-e-ensaios.download');
    Route::get('informacao/imprensa/{novidade}', 'InformacaoController@showNovidade')->name('novidades.show');
    Route::get('informacao/imprensa/download/{novidade}', 'InformacaoController@downloadNovidade')->name('novidades.download');
    Route::get('informacao/outros/{outro}', 'InformacaoController@showOutro')->name('outros.show');
    Route::get('informacao/outros/download/{outro}', 'InformacaoController@downloadOutro')->name('outros.download');

    Route::get('associe-se', 'AssocieSeController@index')->name('associe-se');
    Route::post('associe-se', 'AssocieSeController@post')->name('associe-se.post');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::post('busca', 'BuscaController@post')->name('busca.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Idiomas
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if (in_array($idioma, ['pt'])) {
            Session::put('locale', $idioma);
        }
        if (URL::previous() == route('busca.post')) {
            return redirect()->route('home');
        } else {
            return redirect()->back();
        }
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        Route::resource('banners', 'BannersController');
        Route::resource('objetivos', 'ObjetivosController');
        Route::resource('destaques', 'DestaquesController');
        Route::resource('institucional', 'InstitucionalController', ['only' => ['index', 'update']]);
        Route::resource('diretoria', 'DiretoriaController');
        Route::resource('associados', 'AssociadosController');
        Route::resource('comites', 'ComitesController', ['except' => 'show']);
        Route::resource('comites.associados', 'ComitesAssociadosController', ['only' => ['index', 'create', 'store', 'destroy']]);
        Route::group([
            'prefix'     => 'naotecidos',
            'namespace'  => 'NaoTecidos',
        ], function () {
            Route::resource('o-que-sao', 'NaoTecidosDefinicaoController', ['only' => ['index', 'update']]);
            Route::resource('historia', 'NaoTecidosHistoriaController', ['only' => ['index', 'update']]);
            Route::resource('materias-primas', 'NaoTecidosMatPrimasController', ['only' => ['index', 'update']]);
            Route::resource('como-sao-fabricados', 'NaoTecidosFabricacaoController', ['only' => ['index', 'update']]);
            Route::resource('transf-acabamento-conversao', 'NaoTecidosTransformacaoController', ['only' => ['index', 'update']]);
            Route::resource('classificacao', 'NaoTecidosClassificacaoController', ['only' => ['index', 'update']]);
            Route::resource('identificacao', 'NaoTecidosIdentificacaoController', ['only' => ['index', 'update']]);
            Route::resource('algumas-aplicacoes', 'NaoTecidosAlgumasAplicacoesController');
            Route::resource('aplicacoes-a-z', 'NaoTecidosAplicacoesController');
        });
        Route::group([
            'prefix'     => 'texteis-tecnicos',
            'namespace'  => 'TexteisTecnicos',
        ], function () {
            Route::resource('o-que-sao', 'TexteisTecDefinicaoController', ['only' => ['index', 'update']]);
            Route::resource('materias-primas', 'TexteisTecMatPrimasController', ['only' => ['index', 'update']]);
            Route::resource('como-sao-fabricados', 'TexteisTecFabricacaoController', ['only' => ['index', 'update']]);
            Route::resource('processos-transf-acabamento', 'TexteisTecProcessosController', ['only' => ['index', 'update']]);
            Route::resource('classificacao', 'TexteisTecClassificacaoController', ['only' => ['index', 'update']]);
            Route::resource('desempenho', 'TexteisTecDesempenhoController', ['only' => ['index', 'update']]);
            Route::resource('identificacao', 'TexteisTecIdentificacaoController', ['only' => ['index', 'update']]);
            Route::resource('aplicacoes', 'TexteisTecAplicacoesController', ['only' => ['index', 'update']]);
        });
        Route::group([
            'prefix'     => 'informacao',
            'namespace'  => 'Informacao',
        ], function () {
            Route::resource('publicacoes', 'PublicacoesController');
            Route::resource('cursos-e-eventos', 'EventosController');
            Route::resource('normas-e-ensaios', 'NormasEnsaiosController');
            Route::resource('novidades', 'NovidadesController'); // IMPRENSA
            Route::resource('outros', 'OutrosController');
        });
        Route::resource('associe-se', 'AssocieSeController', ['only' => ['index', 'update']]);
        Route::get('associe-se/contatos/{associe}/toggle', ['as' => 'painel.associe-se.contatos.toggle', 'uses' => 'ContatosAssocieSeController@toggle']);
        Route::resource('associe-se/contatos', 'ContatosAssocieSeController');
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');

        // Limpar caches
        Route::get('clear-cache', function () {
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('config:cache');

            return 'DONE';
        });
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $registros = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/AssociadosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\AssociadosRequest;
use App\Models\Associado;
use App\Models\Grupo;

class AssociadosController extends Controller
{
    public function index()
    {
        $registros = Associado::orderBy('nome', 'ASC')->get();

        return view('painel.associados.index', compact('registros'));
    }

    public function create()
    {
        $grupos = Grupo::pluck('titulo', 'id');
        
        $associadoGrupos = [];

        return view('painel.associados.create', compact('grupos', 'associadoGrupos'));
    }

    public function store(AssociadosRequest $request)
    {
        try {
            $input = $request->all();
            $input['grupo'] = implode('|', $request->grupo);

            if (isset($input['imagem'])) $input['imagem'] = Associado::upload_imagem();

            Associado::create($input);

            return redirect()->route('painel.associados.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Associado $registro)
    {
        $grupos = Grupo::pluck('titulo', 'id');

        $associadoGrupos = explode('|', $registro->grupo);

        return view('painel.associados.edit', compact('registro', 'grupos', 'associadoGrupos'));
    }

    public function update(AssociadosRequest $request, Associado $registro)
    {
        try {
            $input = $request->all();
            $input['grupo'] = implode('|', $request->grupo);

            if (isset($input['imagem'])) $input['imagem'] = Associado::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.associados.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Associado $registro)
    {
        try {
            $registro->delete();

            return redirect()->route('painel.associados.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/AssocieSeController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\AssocieSeRequest;
use App\Models\AssocieSe;

class AssocieSeController extends Controller
{
    public function index()
    {
        $registro = AssocieSe::first();

        return view('painel.associe-se.edit', compact('registro'));
    }

    public function update(AssocieSeRequest $request, AssocieSe $registro)
    {
        try {
            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.associe-se.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\BannersRequest;
use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Banner $registro)
    {
        try {
            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ComitesAssociadosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Associado;
use App\Models\Comite;
use App\Models\ComiteAssociado;

class ComitesAssociadosController extends Controller
{
    public function index(Comite $registro)
    {
        $membros = ComiteAssociado::comite($registro->id)
            ->join('comites', 'comites.id', '=', 'comites_associados.comite_id')
            ->join('associados', 'associados.id', '=', 'comites_associados.associado_id')
            ->select('comites.id as comite_id', 'comites.nome as comite_nome', 'associados.id as associado_id', 'associados.nome as associado_nome', 'associados.imagem as associado_imagem', 'comites_associados.ordem as ordem', 'comites_associados.id as id')
            ->ordenados()->get();

        return view('painel.comites.associados.index', compact('membros', 'registro'));
    }

    public function create(Comite $registro)
    {
        $associados = Associado::orderBy('nome', 'ASC')->pluck('nome', 'id');

        return view('painel.comites.associados.create', compact('associados', 'registro'));
    }

    public function store(Comite $registro, Request $request)
    {
        try {
            $input = $request->all();
            $input['comite_id'] = $registro->id;

            ComiteAssociado::create($input);

            return redirect()->route('painel.comites.associados.index', $registro)->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return 'Erro ao adicionar imagem: ' . $e->getMessage();
        }
    }

    public function destroy(Comite $registro, $membro)
    {
        try {
            $associadoComite = ComiteAssociado::where('id', $membro->id)->where('comite_id', $registro->id)->first();
            
            $associadoComite->delete();

            return redirect()->route('painel.comites.associados.index', $registro)->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagem: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ConfiguracoesRequest;
use App\Models\Configuracoes;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracoes::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracoes $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracoes::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">

  <li class="dropdown @if(Tools::routeIs(['painel.banners*', 'painel.objetivos*', 'painel.destaques*'])) active @endif">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Home<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li @if(Tools::routeIs('painel.banners*')) class="active" @endif>
        <a href="{{ route('painel.banners.index') }}">Banners</a>
      </li>
      <li @if(Tools::routeIs('painel.objetivos*')) class="active" @endif>
        <a href="{{ route('painel.objetivos.index') }}">Objetivos</a>
      </li>
      <li @if(Tools::routeIs('painel.destaques*')) class="active" @endif>
        <a href="{{ route('painel.destaques.index') }}">Destaques</a>
      </li>
    </ul>
  </li>

  <li class="dropdown @if(Tools::routeIs(['painel.institucional*', 'painel.diretoria*', 'painel.comites*'])) active @endif">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">A ABINT<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li @if(Tools::routeIs('painel.institucional*')) class="active" @endif>
        <a href="{{ route('painel.institucional.index') }}">Institucional</a>
      </li>
      <li @if(Tools::routeIs('painel.diretoria*')) class="active" @endif>
        <a href="{{ route('painel.diretoria.index') }}">Diretoria</a>
      </li>
      <li @if(Tools::routeIs('painel.comites*')) class="active" @endif>
        <a href="{{ route('painel.comites.index') }}">Comitês Técnicos</a>
      </li>
    </ul>
  </li>

  <li @if(Tools::routeIs('painel.associados*')) class="active" @endif>
    <a href="{{ route('painel.associados.index') }}">Associados</a>
  </li>

  <li class="dropdown @if(Tools::routeIs(['painel.naotecidos.*'])) active @endif">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">NãoTecidos<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li @if(Tools::routeIs('painel.naotecidos.o-que-sao*')) class="active" @endif>
        <a href="{{ route('painel.naotecidos.o-que-sao.index') }}">O que são</a>
      </li>
      <li @if(Tools::routeIs('painel.naotecidos.historia*')) class="active" @endif>
        <a href="{{ route('painel.naotecidos.historia.index') }}">História</a>
      </li>
      <li @if(Tools::routeIs('painel.naotecidos.materias-primas*')) class="active" @endif>
        <a href="{{ route('painel.naotecidos.materias-primas.index') }}">Matérias-primas</a>
      </li>
      <li @if(Tools::routeIs('painel.naotecidos.como-sao-fabricados*')) class="active" @endif>
        <a href="{{ route('painel.naotecidos.como-sao-fabricados.index') }}">Como são fabricados</a>
      </li>
      <li @if(Tools::routeIs('painel.naotecidos.transf-acabamento-conversao*')) class="active" @endif>
        <a href="{{ route('painel.naotecidos.transf-acabamento-conversao.index') }}">Transf., acabamento e/ou conversão</a>
      </li>
      <li @if(Tools::routeIs('painel.naotecidos.classificacao*')) class="active" @endif>
        <a href="{{ route('painel.naotecidos.classificacao.index') }}">Classificação</a>
      </li>
      <li @if(Tools::routeIs('painel.naotecidos.identificacao*')) class="active" @endif>
        <a href="{{ route('painel.naotecidos.identificacao.index') }}">Identificação</a>
      </li>
      <li @if(Tools::routeIs('painel.naotecidos.algumas-aplicacoes*')) class="active" @endif>
        <a href="{{ route('painel.naotecidos.algumas-aplicacoes.index') }}">Algumas aplicações</a>
      </li>
      <li @if(Tools::routeIs('painel.naotecidos.aplicacoes-a-z*')) class="active" @endif>
        <a href="{{ route('painel.naotecidos.aplicacoes-a-z.index') }}">Aplicações de A a Z</a>
      </li>
    </ul>
  </li>

  <li class="dropdown @if(Tools::routeIs(['painel.texteis-tecnicos.*'])) active @endif">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Têxteis Técnicos<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li @if(Tools::routeIs('painel.texteis-tecnicos.o-que-sao*')) class="active" @endif>
        <a href="{{ route('painel.texteis-tecnicos.o-que-sao.index') }}">O que são</a>
      </li>
      <li @if(Tools::routeIs('painel.texteis-tecnicos.materias-primas*')) class="active" @endif>
        <a href="{{ route('painel.texteis-tecnicos.materias-primas.index') }}">Matérias-primas</a>
      </li>
      <li @if(Tools::routeIs('painel.texteis-tecnicos.como-sao-fabricados*')) class="active" @endif>
        <a href="{{ route('painel.texteis-tecnicos.como-sao-fabricados.index') }}">Como são fabricados</a>
      </li>
      <li @if(Tools::routeIs('painel.texteis-tecnicos.processos-transf-acabamento*')) class="active" @endif>
        <a href="{{ route('painel.texteis-tecnicos.processos-transf-acabamento.index') }}">Processos de transf. e acabamento</a>
      </li>
      <li @if(Tools::routeIs('painel.texteis-tecnicos.classificacao*')) class="active" @endif>
        <a href="{{ route('painel.texteis-tecnicos.classificacao.index') }}">Classificação</a>
      </li>
      <li @if(Tools::routeIs('painel.texteis-tecnicos.desempenho*')) class="active" @endif>
        <a href="{{ route('painel.texteis-tecnicos.desempenho.index') }}">Desempenho</a>
      </li>
      <li @if(Tools::routeIs('painel.texteis-tecnicos.identificacao*')) class="active" @endif>
        <a href="{{ route('painel.texteis-tecnicos.identificacao.index') }}">Identificação</a>
      </li>
      <li @if(Tools::routeIs('painel.texteis-tecnicos.aplicacoes*')) class="active" @endif>
        <a href="{{ route('painel.texteis-tecnicos.aplicacoes.index') }}">Aplicações</a>
      </li>
    </ul>
  </li>

  <li class="dropdown @if(Tools::routeIs(['painel.informacao*'])) active @endif">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Informação<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li @if(Tools::routeIs('painel.informacao.publicacoes*')) class="active" @endif>
        <a href="{{ route('painel.informacao.publicacoes.index') }}">Publicações</a>
      </li>
      <li @if(Tools::routeIs('painel.informacao.cursos-e-eventos*')) class="active" @endif>
        <a href="{{ route('painel.informacao.cursos-e-eventos.index') }}">Cursos e Eventos</a>
      </li>
      <li @if(Tools::routeIs('painel.informacao.normas-e-ensaios*')) class="active" @endif>
        <a href="{{ route('painel.informacao.normas-e-ensaios.index') }}">Normas e Ensaios</a>
      </li>
      <li @if(Tools::routeIs('painel.informacao.novidades*')) class="active" @endif>
        <a href="{{ route('painel.informacao.novidades.index') }}">Novidades/Imprensa</a>
      </li>
      <li @if(Tools::routeIs('painel.informacao.outros*')) class="active" @endif>
        <a href="{{ route('painel.informacao.outros.index') }}">Outros</a>
      </li>
    </ul>
  </li>

  <li class="dropdown @if(Tools::routeIs('painel.associe-se*')) active @endif">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Associe-se
      @if($contatosNaoLidosAssocieSe >= 1)
      <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidosAssocieSe }}</span>
      @endif
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li @if(Tools::routeIs('painel.associe-se.index')) class="active" @endif>
        <a href="{{ route('painel.associe-se.index') }}">Associe-se</a>
      </li>
      <li @if(Tools::routeIs('painel.associe-se.contatos*')) class="active" @endif>
        <a href="{{ route('painel.associe-se.contatos.index') }}">
          Contatos Associe-se
          @if($contatosNaoLidosAssocieSe >= 1)
          <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidosAssocieSe }}</span>
          @endif
        </a>
      </li>
    </ul>
  </li>

  <li class="dropdown @if(Tools::routeIs(['painel.contato.index', 'painel.contato.recebidos*'])) active @endif">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Contato
      @if($contatosNaoLidos >= 1)
      <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
      @endif
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li @if(Tools::routeIs('painel.contato.index')) class="active" @endif>
        <a href="{{ route('painel.contato.index') }}">Informações de Contato</a>
      </li>
      <li @if(Tools::routeIs('painel.contato.recebidos*')) class="active" @endif>
        <a href="{{ route('painel.contato.recebidos.index') }}">
          Contatos Recebidos
          @if($contatosNaoLidos >= 1)
          <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
          @endif
        </a>
      </li>
    </ul>
  </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('app.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/vendor.painel.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel.css') }}">
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/js/vendor.painel.js') }}"></script>
    <script src="{{ asset('assets/js/painel.js') }}"></script>
</body>
</html>